version: ~> 1.0

env:
  global:
    # Doctr deploy key for pcdshub/fluke_985
    - secure: "BCFHwHCn0vea+5CG4oFcjgKG2uwQFQeBsyY05IlgkxAIgV8Y54lmKQtKaGi5O/ekSd5VUHOtz+R8o8xmNlvIkgGP+dQLU6vBXcnKagMNe0/WrpnwYBM8L1w8KjUPGjnZdbhWjWgaSEsJ9uAiGEGrfKqsbIeBdMdzzLmpsVGk/feM5HqrEUU8NSt1G9HmnVG96f4J30KyB5DiAzUbLz6U9NAk6eP8m8prVmbpLfQHdndx3X65jZouRM2WyfWJv0n3BJYRyBP64Zgggnf8oKrLA7DrziWAmoBTbv1u9D9xBHXPlGkGYMtE9e1yVeHx0Ex64ypW/1E9G4epr5+BIhgud0Ckcpy2hRL0mu8LKwHOUTTRJdQ0VktBkOb8tZ/hKncZP2Q+AFHRpG6DAQKLiPjATjLyIZ2sHx539PbT/vR6MYmfzdty5owWg9QSZiRsFxIHUSr9j4jvRGAd+C7DvcWBr/rfrVkZOZuS7maCZvWm5W7k09kqmvTe1RnjN1z4XZiTJIAMtIXnDF8Mxfhwnv7E/Y/7nnU/XkTAsmW/iGDCOVp4ZwKQHFk9IF+/D8Y4IpuKOEpNLPigvVJK7arbYVUyZpmMQtITBnTYtRvXorfh//4St8XBaPsStFU1kHXde3lmYPVsBOyyH5f69EtKqOCAF+LDDX35lqLt05hfMtyqd5k="
    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"
    # Dependency files used to build the documentation (space separated)
    - DOCS_REQUIREMENTS="dev-requirements.txt requirements.txt"
    # Options to be passed to flake8 for package linting. Usually this is just
    # the package name but you can enable other flake8 options via this config
    - PYTHON_LINT_OPTIONS="fluke_985"

    # The name of the conda package
    - CONDA_PACKAGE="fluke_985"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"

    # Requirements file with contents for tests dependencies
    - CONDA_REQUIREMENTS="dev-requirements.txt"

# Uncomment this block if you would like to make PIP test an allowed failure
#jobs:
#  allow_failures:
#    # This makes the PIP based Python 3.6 optional for passing.
#    # Remove this block if passing tests with PIP is mandatory for your
#    # package
#    - name: "Python 3.6 - PIP"

import:
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda.yml
